os:
  - linux
  - osx

language: node_js
node_js: node

addons:
  ssh_known_hosts: c4dtsrv1.epfl.ch

install:
  - jq=`mktemp`
  - curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o $jq
  - chmod +x $jq
  - export PATH=$PATH:`dirname $jq`
before_script:
  - npx prettier --check .
  - set -e; for d in library webapp; do
    ( cd $d && npm ci && npx eslint --ext ts --max-warnings 0 . ); done
  - rm protobuf/drynx.proto # ensure correct generation
script: make
after_success:
  - set -e
  - out=`git status --porcelain`; [ -z "$out" ] || ( git diff; exit 1 )

before_deploy:
  - echo "$DEPLOY_SSH_KEY" > "$HOME/.ssh/id_rsa"
  - chmod 600 "$HOME/.ssh/id_rsa"
  - echo "//registry.npmjs.org/:_authToken=${DEPLOY_NPM_TOKEN}" > "$HOME/.npmrc"
deploy:
  - provider: script
    script: rsync -a --del webapp/dist/ drynx@c4dtsrv1.epfl.ch:www
    skip_cleanup: true
    on:
      branch: main
      condition: $TRAVIS_OS_NAME = linux
  - provider: script
    script: cd library && npm version prerelease --preid=p`date +%Y%m%d%H%M%S` && npm publish --tag dev
    skip_cleanup: true
    on:
      branch: main
      condition: $TRAVIS_OS_NAME = linux

cache:
  npm: false
