language: node_js
node_js: node

addons:
  ssh_known_hosts: c4dtsrv1.epfl.ch

script: make library-test webapp-build

before_deploy:
  - echo "$DEPLOY_SSH_KEY" > "$HOME/.ssh/id_rsa"
  - chmod 600 "$HOME/.ssh/id_rsa"
deploy:
  skip_cleanup: true
  provider: script
  script: rsync -a --del webapp/dist/ drynx@c4dtsrv1.epfl.ch:www
  on:
    branch: master
